
export interface User {
    _id? : string,
    firstname : string,
    middlename : string | null,
    surname : string,
    email : string,
    gender : string,
    dob : string,
    address: string,
    branch: string,
    transportation_type: string,
    vehicleNumber: string,
    verifiedId: string,
    verifiedIdType: string,
    zone : string,
    unit : string,
    phone_no : string,
    state : string,
    next_of_kin_name : string,
    next_of_kin_address : string,
    next_of_kin_phone_no : string,
    uniqueId : string,
    updatedAt? : Date,
    agentId? : any,
    image : File | string,
    imageId? : string,
    imageBlob? : string,
    signature?: File,
    fingerId?: string
    finger1 : string,
    finger2 : string,
    approved? : boolean,
    __v? : any
}